---
title: "metaG_Figs"
author: "SRomano"
output: html_document
editor_options: 
  chunk_output_type: console
---
# load packages
```{r}
library(ggplot2)
library(dplyr)
```

# Load the data

```{r}
# clr
s5<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_5per_log.rds")
s10<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_10per_log.rds")
s20<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_20per_log.rds")
s30<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_30per_log.rds")

#clr
s5c<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_5per_clr.rds")
s10c<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_10per_clr.rds")
s20c<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_20per_clr.rds")
s30c<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_30per_clr.rds")
s30c$prev<-rep("30% in 2 std", nrow(s30c))
```

```{r}
# estimate the number of features left
length(readRDS("/metaG/R_analyses/Taxonomy/RDS/spec_5x10.rds")) 
length(readRDS("/metaG/R_analyses/Taxonomy/RDS/spec_10x10.rds"))
length(readRDS("/metaG/R_analyses/Taxonomy/RDS/spec_20x10.rds")) 
length(readRDS("/metaG/R_analyses/Taxonomy/RDS/spec_30x10.rds"))


# rename

s5$prev<-rep("5% in 2 studies (1808 feat.)", length = nrow(s5))
s10$prev<-rep("10% in 2 studies (1263 feat.)", length = nrow(s10))
s20$prev<-rep("20% in 2 studies (821 feat.)", length = nrow(s20))
s30$prev<-rep("30% in 2 studies (576 feat.)", length = nrow(s30))

s5c$prev<-rep("5% in 2 studies (1808 feat.)", length = nrow(s5c))
s10c$prev<-rep("10% in 2 studies (1263 feat.)", length = nrow(s10c))
s20c$prev<-rep("20% in 2 studies (821 feat.)", length = nrow(s20c))
s30c$prev<-rep("30% in 2 studies (576 feat.)", length = nrow(s30c))


df<-rbind.data.frame(s5, s10, s20, s30, s5c, s10c, s20c, s30c)
df$prev<-factor(df$prev,
                levels = c("5% in 2 studies (1808 feat.)", 
                           "10% in 2 studies (1263 feat.)", 
                           "20% in 2 studies (821 feat.)", 
                           "30% in 2 studies (576 feat.)"))


g<-ggplot(df, aes(prev, AUC, fill=norm)) +
  geom_boxplot() +
  facet_wrap(~ML, nrow = 1) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = c("#A669EE", "#CC79A7")) +
  xlab("Feature filtrations") +
  labs(fill = "Normalization")+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        strip.text = element_text(size = 9.5))

ggsave(filename = "/metaG/R_analyses/Taxonomy/Figures/AUC_PrevMLnorm.svg", plot = g, device = "svg", width = 8.5, height = 6)

```

#CSV

```{r}
perf_sing_log<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_5per_log.rds")
#take only 5%
perf_sing_log<-subset(perf_sing_log, prev == "5% in 2 std")
perf_sing_log$batch<-rep("Not corrected", nrow(perf_sing_log))
# format to merge with the other
perf_log<-data.frame(
  training.data = perf_sing_log$study,
  testing.data  = perf_sing_log$study,
  AUC = perf_sing_log$AUC,
  ML = perf_sing_log$ML,
  norm = perf_sing_log$norm
)


csv_log<-readRDS("/metaG/R_analyses/Taxonomy/RDS/metaG_CSV_5perc_Log_df_auc.rds")

df_comb<-rbind.data.frame(perf_log, csv_log)


df_comb$AUC<-as.numeric(df_comb$AUC)
df_comb$AUC<-round(df_comb$AUC, digits = 2)*100

df.diag<-df_comb[1:42,]

r<-ggplot(df_comb, aes(x =  testing.data,training.data,  fill = AUC)) +
  geom_tile(color = "black") +
  geom_text(aes(label = AUC), color = "black", size = 4) +
  coord_fixed() +
  scale_fill_viridis_c(option = "H",
                       breaks=c(50,70,100),
                       limits=c(40,100))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust=0.95,vjust=0.2),
        strip.text = element_text(size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.position = "right") +
  facet_wrap(~ ML)+
  geom_tile(data = df.diag, fill = NA, color = "white", linewidth = 2)+
  facet_wrap(~ ML) +
  xlab("Test data") +
  ylab("Training data")

r
ggsave(plot = r, filename = "/metaG/R_analyses/Taxonomy/Figures/CSV_5perc_log.jpeg", 
       device = "jpeg", 
       width = 10, 
       height = 8)

```
# Check effect of metadata on AUCs
```{r}
df_comb<-subset(df_comb,ML == "ridge")
est<-c("Jo_2022", "Mao_2021", "Qian_2020")
west<-c("Bedarf_2017", "Boktor_2_2023", "Boktor_1_2023", "Wallen_2022")

# add west east
df_comb$train <-ifelse(df_comb$training.data %in% west, "W", "E")
df_comb$test <-ifelse(df_comb$testing.data %in% west, "W", "E")
df_comb$schema<-paste0(df_comb$train, "_", df_comb$test)
df_comb$val<-ifelse(df_comb$training.data == df_comb$testing.data, "CV", "CSV")
saveRDS(df_comb, "/metaG/R_analyses/Taxonomy/RDS/df_comb.rds")

###############################################################################
# test effect of east west
################################################################################

anova(aov(AUC ~ schema, data = subset(df_comb, val == "CSV")))
model <- aov(AUC ~ schema, data = subset(df_comb, val == "CSV"))
(tukey_result <- TukeyHSD(model))

# load age and gender
age<-readRDS("/metaG/R_analyses/Taxonomy/RDS/meta.diff.age.rds")
# remove the NA
age<-na.omit(age)
gen<-readRDS("/metaG/R_analyses/Taxonomy/RDS/meta.diff.gender.rds")

# remove the NA and do another ratio
gen<-na.omit(gen) %>%
  group_by(Study) %>%
  mutate(delta.delta = lag(delta.winCases)/delta.winCases) %>%
  na.omit(gen)
  

df.comb.ag<-rbind.data.frame(
  age %>%
    select(Study, delta) %>%
    right_join(df_comb, by = c("Study" = "training.data" )) %>%
    mutate(factor = "age",
           tt = "train") %>%
    select(-testing.data),
  gen %>%
    select(Study, delta.delta) %>%
    dplyr::rename(delta=delta.delta) %>%
    right_join(df_comb, by = c("Study" = "training.data" )) %>%
    mutate(factor = "sex",
           tt = "train")%>%
    select(-testing.data),
  age %>%
    select(Study, delta) %>%
    right_join(df_comb, by = c("Study" = "testing.data" )) %>%
    mutate(factor = "age",
           tt = "test")%>%
    select(-training.data),
  gen %>%
    select(Study, delta.delta) %>%
    dplyr::rename(delta = delta.delta) %>%
    right_join(df_comb, by = c("Study" = "testing.data" )) %>%
    mutate(factor = "sex",
           tt = "test")%>%
        select(-training.data))
saveRDS(df.comb.ag, "/metaG/R_analyses/Taxonomy/RDS/df.comb.ag.rds")


##################################################################
## test associations between pop feats and AUCs 
###################################################################

# lm for gender train CSV
tmp<-subset(df.comb.ag, tt == "train" & val == "CSV" & factor == "sex")
mod<-lm(AUC~delta, data = tmp)
summary(mod)
confint(mod)
message("The variance explained by Gender in CSV SMG and train data is ", summary(mod)$r.squared)
r2.gender.smg.csv.train<-summary(mod)$r.squared


# lm for gender test CSV
tmp<-subset(df.comb.ag, tt == "test" & val == "CSV" & factor == "sex")
mod<-lm(AUC~delta, data = tmp)
summary(mod)
confint(mod)
message("The variance explained by Gender in CSV SMG and test data is ", summary(mod)$r.squared)
r2.gender.smg.csv.test<-summary(mod)$r.squared


# lm for age train CSV
tmp<-subset(df.comb.ag, tt == "train" & val == "CSV" & factor == "age")
mod<-lm(AUC~delta, data = tmp)
summary(mod)
confint(mod)
message("The variance explained by Age in CSV SMG and train data is ", summary(mod)$r.squared)
r2.age.smg.csv.train<-summary(mod)$r.squared


# lm for Age test CSV
tmp<-subset(df.comb.ag, tt == "test" & val == "CSV" & factor == "age")
mod<-lm(AUC~delta, data = tmp)
summary(mod)
confint(mod)
message("The variance explained by Age in CSV SMG and test data is ", summary(mod)$r.squared)
r2.age.smg.csv.test<-summary(mod)$r.squared


# lm for gender  CV
tmp<-subset(df.comb.ag, val == "CV" & factor == "sex")
mod<-lm(AUC~delta, data = tmp)
summary(mod)
confint(mod)
message("The variance explained by Gender in CV SMG is ", summary(mod)$r.squared)
r2.gender.smg.cv<-summary(mod)$r.squared


# lm for Age  CSV
tmp<-subset(df.comb.ag,  val == "CV" & factor == "age")
mod<-lm(AUC~delta, data = tmp)
summary(mod)
confint(mod)
message("The variance explained by Age in CV SMG is ", summary(mod)$r.squared)
r2.age.smg.cv<-summary(mod)$r.squared



# ANOVA E/W CSV [here there are duplicate that need to be removed]
tmp<-subset(df_comb, val == "CSV") 
mod<-lm(AUC~schema, data = tmp)
summary(aov(mod))
message("The variance explained by W/E comb in CSV 16S is ", summary(mod)$r.squared)
r2.ew.smg.csv<-summary(mod)$r.squared

# ANOVA E/W CV [here there are duplicate that need to be removed]
tmp<-subset(df_comb, val == "CV") 
mod<-lm(AUC~schema, data = tmp)
summary(aov(mod))
message("The variance explained by W/E comb in CV 16S is ", summary(mod)$r.squared)
r2.ew.smg.cv<-summary(mod)$r.squared


df.smg<-data.frame(r2 = c(r2.gender.smg.csv.train, r2.gender.smg.csv.test, 
                          r2.age.smg.csv.train, r2.age.smg.csv.test, 
                          r2.gender.smg.cv, r2.age.smg.cv, r2.ew.smg.csv,
                          r2.ew.smg.cv),
                   validation = c(rep("CSV", 4), rep("CV", 2), "CSV", "CV"),
                   train.test = c("train", "test", "train", "test", NA, NA, NA, NA),
                   factor = c("Gender", "Gender", "Age", "Age", "Gender", "Age", "E/W", "E/W"),
                   seqs = rep("SMG", 8))

saveRDS(df.smg, "/metaG/R_analyses/Taxonomy/RDS/rsq.age.sex.rds")
```
