---
title: "AUCs"
author: "SRomano"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load packages
```{r}
library(ggplot2)
library(dplyr)
library(Hmisc)

```

# metaG
## Load dfs and format
```{r}
df_comb<-readRDS("//metaG/R_analyses/Taxonomy/RDS/df.comb.cv.scv.rds")
df_comb<-subset(df_comb, ML == "ridge")

ls.out<-readRDS("/metaG/R_analyses/Taxonomy/RDS/ls.out.cv.scv.rds")

# create dfs with summary stats
df.mean.stdv <-
  df_comb %>%
  group_by(method) %>%
  summarise(mean = mean(AUC),
            stdev = sd(AUC))

ls.mean.std <-
  ls.out %>%
  group_by(method) %>%
  summarise(mean = mean(AUC),
            stdev = sd(AUC))

df.points<-data.frame( study = c(subset(df_comb, method == "CV")$training.data, ls.out$study.out),
                       AUC =  c(subset(df_comb, method == "CV")$AUC, ls.out$AUC),
                       method =  c(subset(df_comb, method == "CV")$method, ls.out$method))
```

## t-tests
```{r}
df.scv<-df_comb[-1*c(1:7),]
df.csv.m<-df.scv %>%
  group_by(training.data) %>%
  summarise(AUC = mean(AUC))

# t-test compare CSV vs LOSO
df.tt<-data.frame(AUC = c(ls.out$AUC, df.csv.m$AUC),
                  method = as.factor(c(rep("LOSO", 7), rep("CSV", 7))))
t.test(AUC ~ method, data = df.tt, var.equal = F)
```


## Plots
```{r}
(p<- 
    ggplot() + 
    # add shading of the stdev 
    geom_rect(mapping =
                 aes(ymin =
                        subset(df.mean.stdv, method == "CV")$mean - subset(df.mean.stdv, method == "CV")$stdev,
                      ymax =
                        subset(df.mean.stdv, method == "CV")$mean + subset(df.mean.stdv, method == "CV")$stdev,
                      xmin = -Inf, xmax = Inf),
                fill = "#0072B2", alpha = 0.2) +

   geom_rect(mapping = aes(ymin = ls.mean.std$mean - ls.mean.std$stdev,
                           ymax = ls.mean.std$mean + ls.mean.std$stdev,
                           xmin = -Inf, xmax = Inf),
             fill = "#FFED00", alpha = 0.2)  +
   # add lines for average
      geom_hline(yintercept =
                   subset(df.mean.stdv, method == "CV")$mean,
                 linetype = "solid",
                 linewidth = .9,
                 color = "#0072B2")+
    geom_hline(yintercept = ls.mean.std$mean,
               linetype = "solid",
               linewidth = .9,
               color = "#FFED00")+

    # add violins
    geom_violin(data = subset(df_comb, method == "CSV"),
                mapping = aes(x = training.data, y = AUC),
                fill ="white",
                color = "black",
                trim = T,
                size = 0.75) +
    # add stats summaries
    stat_summary(data = subset(df_comb, method == "CSV"),
                mapping = aes(x = training.data, y = AUC),
                fun.data = "mean_sdl",  fun.args = list(mult = 1),
                geom = "pointrange", color = "black", size = 1.3) +
    stat_summary(data = subset(df_comb, method == "CSV"),
                mapping = aes(x = training.data, y = AUC),
                fun.data = "mean_sdl",  fun.args = list(mult = 1),
                geom = "pointrange", color = "gray", size = 1) +

    # # # add points
    geom_point(data = df.points, 
               mapping = aes(study, 
                           AUC, 
                           shape = method), 
               size = 5,
               color = "black",
               position = position_dodge2(width = 0.5)) +

    geom_point(data = df.points, 
               mapping = aes(study, 
                           AUC, 
                           shape = method,
                           color = method), 
               size = 4,
               position = position_dodge2(width = 0.5)) +


  # adjust colors and theme
  
  scale_color_manual(values = c("#0072B2","#FFED00")) +
  geom_hline(yintercept=50, 
             linetype="dashed", 
             color = "#757373", size=1) +
  theme_bw() +
  scale_y_continuous(breaks = seq(40, 95, by = 5), limits =c(40,95)) +
  # labs(title = "Metagenomics data") +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size =14),
        title = element_text(size =16),
        axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position =c(0.85, 0.08),
        legend.background = element_blank(),
        legend.text = element_text(size = 12),
        legend.title=element_blank()) +
    xlab("Study"))
```


# 16S
## Load dfs and format
```{r}

df_comb16<-readRDS("/16S/R_analyses/RDS/df.comb.cv.scv.rds")
df_comb16<-subset(df_comb16, ML == "ridge")
ls.out16<-readRDS("/16S/R_analyses/RDS/ls.out.cv.scv.rds")

# Need to re-add the dates
df_comb16$training.data[df_comb16$training.data == "Aho"]<-"Aho_2019"
df_comb16$training.data[df_comb16$training.data == "Petrov"]<-"Petrov_2017"
df_comb16$training.data[df_comb16$training.data == "Keshavarzian"]<-"Keshavarzian_2015"
df_comb16$training.data[df_comb16$training.data == "Zhang"]<-"Zhang_2020"
df_comb16$training.data[df_comb16$training.data == "Nishiwaki"]<-"Nishiwaki_2020"
df_comb16$training.data[df_comb16$training.data == "Hopfner"]<-"Hopfner_2017"
df_comb16$training.data[df_comb16$training.data == "Weis"]<-"Weis_2019"
df_comb16$training.data[df_comb16$training.data == "Cirstea"]<-"Cirstea_2020"
df_comb16$training.data[df_comb16$training.data == "Tan"]<-"Tan_2021"
df_comb16$training.data[df_comb16$training.data == "Kenna"]<-"Kenna_2021"
df_comb16$training.data[df_comb16$training.data == "Wallen251"]<-"Wallen251_2021"
df_comb16$training.data[df_comb16$training.data == "Wallen151"]<-"Wallen151_2021"
df_comb16$training.data[df_comb16$training.data == "Jo"]<-"Jo_2022"
df_comb16$training.data[df_comb16$training.data == "Lubomski"]<-"Lubomski_2022"
df_comb16$training.data[df_comb16$training.data == "Heintz_Bushart"]<-"Heintz_Bushart_2017"
df_comb16$training.data[df_comb16$training.data == "Qian"]<-"Qian_2018"
df_comb16$training.data[df_comb16$training.data == "Pietrucci"]<-"Pietrucci_2019"

ls.out16$study.out[ls.out16$study.out == "Aho"]<-"Aho_2019"
ls.out16$study.out[ls.out16$study.out == "Petrov"]<-"Petrov_2017"
ls.out16$study.out[ls.out16$study.out == "Keshavarzian"]<-"Keshavarzian_2015"
ls.out16$study.out[ls.out16$study.out == "Zhang"]<-"Zhang_2020"
ls.out16$study.out[ls.out16$study.out == "Nishiwaki"]<-"Nishiwaki_2020"
ls.out16$study.out[ls.out16$study.out == "Hopfner"]<-"Hopfner_2017"
ls.out16$study.out[ls.out16$study.out == "Weis"]<-"Weis_2019"
ls.out16$study.out[ls.out16$study.out == "Cirstea"]<-"Cirstea_2020"
ls.out16$study.out[ls.out16$study.out == "Tan"]<-"Tan_2021"
ls.out16$study.out[ls.out16$study.out == "Kenna"]<-"Kenna_2021"
ls.out16$study.out[ls.out16$study.out == "Wallen251"]<-"Wallen251_2021"
ls.out16$study.out[ls.out16$study.out == "Wallen151"]<-"Wallen151_2021"
ls.out16$study.out[ls.out16$study.out == "Jo"]<-"Jo_2022"
ls.out16$study.out[ls.out16$study.out == "Lubomski"]<-"Lubomski_2022"
ls.out16$study.out[ls.out16$study.out == "Heintz_Bushart"]<-"Heintz_Bushart_2017"
ls.out16$study.out[ls.out16$study.out == "Qian"]<-"Qian_2018"
ls.out16$study.out[ls.out16$study.out == "Pietrucci"]<-"Pietrucci_2019"


# create dfs with summary stats
df.mean.stdv16 <-
  df_comb16 %>%
  group_by(method) %>%
  summarise(mean = mean(AUC),
            stdev = sd(AUC))

ls.mean.std16 <-
  ls.out16 %>%
  group_by(method) %>%
  summarise(mean = mean(AUC),
            stdev = sd(AUC))

df.points16<-data.frame( study = c(subset(df_comb16, method == "CV")$training.data, ls.out16$study.out),
                       AUC =  c(subset(df_comb16, method == "CV")$AUC, ls.out16$AUC),
                       method =  c(subset(df_comb16, method == "CV")$method, ls.out16$method))
```

## t-test
```{r}
df.scv<- subset(df_comb16, method == "CSV")
df.csv.m<-df.scv %>%
  group_by(training.data) %>%
  summarise(AUC = mean(AUC))

# t-test compare CSV vs LOSO
df.tt<-data.frame(AUC = c(ls.out16$AUC, subset(df_comb16, method == "CSV")$AUC),
                  method = as.factor(c(rep("LOSO", 17), rep("CSV", nrow(subset(df_comb16, method == "CSV"))))))
t.test(AUC ~ method, data = df.tt, var.equal = F)


# t-tes welch comparing CSV 16S and SMG 
df.tt<-data.frame(AUC = c(subset(df_comb16, method == "CSV")$AUC ,
                          subset(df_comb, method == "CSV")$AUC),
                  method = as.factor(c(rep("16S", 272), 
                                       rep("SMG", 42))))
t.test(AUC ~ method, data = df.tt, var.equal = F)
# t-tes welch comparing LOSO 16S and SMG 
df.tt<-data.frame(AUC = c(ls.out16$AUC, ls.out$AUC),
                  method = as.factor(c(rep("16S", 17), 
                                       rep("SMG", 7))))
t.test(AUC ~ method, data = df.tt, var.equal = F)
```

## Plot
```{r}
(p16<- 
    ggplot() + 
    # add shading of the stdev 
    geom_rect(mapping =
                  aes(ymin =
                        subset(df.mean.stdv16, method == "CV")$mean - subset(df.mean.stdv16, method == "CV")$stdev,
                      ymax =
                        subset(df.mean.stdv16, method == "CV")$mean + subset(df.mean.stdv16, method == "CV")$stdev,
                      xmin = -Inf, xmax = Inf),
                fill = "#0072B2", alpha = 0.2) +

    geom_rect(mapping = aes(ymin = ls.mean.std16$mean - ls.mean.std16$stdev,
                            ymax = ls.mean.std16$mean + ls.mean.std16$stdev,
                            xmin = -Inf, xmax = Inf),
              fill = "#FFED00", alpha = 0.2)  +
    # add lines for average
      geom_hline(yintercept =
                   subset(df.mean.stdv16, method == "CV")$mean,
                 linetype = "solid",
                 linewidth = .9,
                 color = "#0072B2")+
    geom_hline(yintercept = ls.mean.std16$mean,
               linetype = "solid",
               linewidth = .9,
               color = "#FFED00")+
  
  # add violins
  geom_violin(data = subset(df_comb16, method == "CSV"),
              mapping = aes(x = training.data, y = AUC),
              fill ="white",
              color = "black",
              trim = T,
              size = 0.75) +
  # add stats summaries
  stat_summary(data = subset(df_comb16, method == "CSV"),
              mapping = aes(x = training.data, y = AUC),
              fun.data = "mean_sdl",  fun.args = list(mult = 1),
              geom = "pointrange", color = "black", size = 1.3) +
  stat_summary(data = subset(df_comb16, method == "CSV"),
              mapping = aes(x = training.data, y = AUC),
              fun.data = "mean_sdl",  fun.args = list(mult = 1),
              geom = "pointrange", color = "gray", size = 1) +

    # add points
    geom_point(data = df.points16, 
               mapping = aes(study, 
                           AUC, 
                           shape = method), 
               size = 5,
               color = "black",
               position = position_dodge2(width = 0.5)) +

    geom_point(data = df.points16, 
               mapping = aes(study, 
                           AUC, 
                           shape = method,
                           color = method), 
               size = 4,
               position = position_dodge2(width = 0.5)) +


  # adjust colors and theme
  
  scale_color_manual(values = c("#0072B2","#FFED00")) +
  geom_hline(yintercept=50, 
             linetype="dashed", 
             color = "#757373", size=1) +
  theme_bw() +
  scale_y_continuous(breaks = seq(40, 95, by = 5), limits =c(40,95)) +
  # labs(title = "16S amplicon data") +
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size =14),
        title = element_text(size =16),
        axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1),
        axis.ticks.y = element_blank(),
        legend.position =c(0.9, 0.08),
        legend.background = element_blank(),
        legend.text = element_text(size = 12),
        legend.title=element_blank()) +
    xlab("Study"))

```

# Combine two plots
```{r}

(gg<-ggpubr::ggarrange(plotlist = list(p16, p), 
                       align = "hv", 
                       widths = c(2.5,1),
                       labels = "AUTO", 
                       label.x = c(0.05,0.1),
                       label.y = c(0.98, 0.98), 
                       font.label = list(size =21)))

ggsave("/16S/R_analyses/Figures/CSV_violin_1b.svg", gg, device = "svg", width = 14, height = 6)

```
