---
title: "Violin_AUCs"
author: "SRomano"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(dplyr)
library(ggnewscale)
```

# Load data and metadata

```{r}
meta<-readRDS("/metaG/R_analyses/Taxonomy/RDS/meta.rds")
```

```{r}
# GMM
gmm<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/GMM_single_5per_log.rds")
gmm$funct<-rep("GMM", nrow(gmm))

gmm.l<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/GMM_loso_ridge.rds")
gmm.l<-gmm.l@auc
gmm.l$funct<-rep("GMM", nrow(gmm.l))
gmm.csv<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/CSV_GMM_Log_df_auc.rds")
gmm.csv<-subset(gmm.csv, ML == "ridge")
gmm.csv$funct<-rep("GMM", nrow(gmm.csv))


KO<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/Single_5per_log.rds")
KO$funct<-rep("KO", nrow(KO))
load("/metaG/R_analyses/Functions/AA_KO/RData/metaG_Sinlge_5perc_log_Wallen.RData")
df<-data.frame(
  study = rep("Wallen_2022", 6),
  prev = rep("5% in 2 std ", 6),
  ML = c("lasso", "lasso_ll", "enet", "ridge", "ridge_ll", "random_forest"),
  AUC = c(lasso_5x10@auc$Wallen_2022$auc, 
          lassoll_5x10@auc$Wallen_2022$auc, 
          enet_5x10@auc$Wallen_2022$auc, 
          ridge_5x10@auc$Wallen_2022$auc, 
          ridge_ll_5x10@auc$Wallen_2022$auc, 
          rf_5x10@auc$Wallen_2022$auc),
  norm = rep("log", 6),
  funct = rep("KO", 6)
)
KO<-rbind.data.frame(KO, df)

KO.l<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/All_metaG_loso_ridge.rds")
KO.l<-KO.l@auc
KO.l$funct<-rep("KO", nrow(KO.l))
KO.csv<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/metaG_CSV_5perc_Log_df_auc.rds")
csv_wallen.out<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/Wallen_CSV.rds")
csv_wallen.out$norm<-rep("LOG", nrow(csv_wallen.out))
KO.csv<-rbind.data.frame(KO.csv, csv_wallen.out)
KO.csv<-subset(KO.csv, ML == "ridge")
KO.csv$funct<-rep("KO", nrow(KO.csv))

KOpath<-readRDS("/metaG/R_analyses/Functions/AA_KOpath//RDS/Single_5per_log.rds")
KOpath$funct<-rep("KEGGpath", nrow(KOpath))
KOpath.l<-readRDS("/metaG/R_analyses/Functions/AA_KOpath//RDS/All_metaG_loso_ridge.rds")
KOpath.l<-KOpath.l@auc
KOpath.l$funct<-rep("KEGGpath", nrow(KOpath.l))
KOpath.csv<-readRDS("/metaG/R_analyses/Functions/AA_KOpath/RDS/metaG_CSV_5perc_Log_df_auc.rds")
KOpath.csv<-subset(KOpath.csv, ML == "ridge")
KOpath.csv$funct<-rep("KEGGpath", nrow(KOpath.csv))


gbm<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/GBM_single_5per_log.rds")
gbm$funct<-rep("GBM", nrow(gbm))
gbm.l<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/GBM_loso_ridge.rds")
gbm.l<-gbm.l@auc
gbm.l$funct<-rep("GBM", nrow(gbm.l))
gbm.csv<-readRDS("/metaG/R_analyses/Functions/AA_KO/RDS/GBM_CSV_Log_df_auc.rds")
gbm.csv<-subset(gbm.csv, ML == "ridge")
gbm.csv$funct<-rep("GBM", nrow(gbm.csv))

KOm<-readRDS("/metaG/R_analyses/Functions/AB_KOmod/RDS/Single_5per_log.rds")
KOm$funct<-rep("KEGGmod", nrow(KOm))
KOm.l<-readRDS("/metaG/R_analyses/Functions/AB_KOmod//RDS/All_metaG_loso_ridge.rds")
KOm.l<-KOm.l@auc
KOm.l$funct<-rep("KEGGmod", nrow(KOm.l))
KOm.csv<-readRDS("/metaG/R_analyses/Functions/AB_KOmod/RDS/metaG_CSV_5perc_Log_df_auc.rds")
KOm.csv<-subset(KOm.csv, ML == "ridge")
KOm.csv$funct<-rep("KEGGmod", nrow(KOm.csv))


tax<-readRDS("/metaG/R_analyses/Taxonomy/RDS/Single_5per_log.rds")
tax$funct<-rep("taxonomy", nrow(tax))
tax.l<-readRDS("/metaG/R_analyses/Taxonomy/RDS/All_metaG_loso_ridge.rds")
tax.l<-tax.l@auc
tax.l$funct<-rep("taxonomy", nrow(tax.l))
tax.csv<-readRDS("/metaG/R_analyses/Taxonomy/RDS/metaG_CSV_5perc_Log_df_auc.rds")
tax.csv<-subset(tax.csv, ML == "ridge")
tax.csv$funct<-rep("taxonomy", nrow(tax.csv))

# combine cv
df.all<-rbind.data.frame(gmm, KO, KOm, KOpath, gbm, tax)
df.all$funct<-factor(df.all$funct, levels = c("taxonomy","KO", "KEGGmod", "KEGGpath", "GMM", "GBM"), ordered = T)
df.all$type<-rep("within-study CV", nrow(df.all))

# combine loso
l.all<-rbind.data.frame(gmm.l, KO.l, KOm.l, KOpath.l, gbm.l, tax.l)
l.all$type<-rep("LOSO", nrow(l.all))
l.all$AUC<-round(l.all$AUC, 2)*100

# combine csv
csv.all<-rbind.data.frame(KO.csv, KOm.csv, KOpath.csv, tax.csv, gmm.csv, gbm.csv)
csv.all$type<-rep("CSV", nrow(csv.all))
csv.all$AUC<-as.numeric(csv.all$AUC)
csv.all$AUC<-csv.all$AUC*100

ridge.all.tax.f<-subset(df.all, ML  == "ridge")

ridge.all.tax.f$AUC<-ridge.all.tax.f$AUC*100
names(ridge.all.tax.f)<-c("study", "prev", "ML", "AUC", "norm", "profile", "type")

```
# make paired tests
```{r}
df.all.test<-data.frame(model = c(rownames(csv.all), l.all$study.out, ridge.all.tax.f$study),
                        AUC = c(csv.all$AUC, l.all$AUC, ridge.all.tax.f$AUC),
                        val = c(csv.all$type, l.all$type, ridge.all.tax.f$type),
                          prof = c(as.character(csv.all$funct), as.character(l.all$funct), as.character(ridge.all.tax.f$profile)))

df.all.test<-df.all.test[order(df.all.test$model),]

ggplot(df.all.test, aes(prof, AUC, fill = val)) +
  geom_boxplot()

# lm + emmeans            
l.perf<-split(df.all.test, as.factor(df.all.test$val))
l.emm<-vector(mode = "list", length = length(l.perf))
names(l.emm)<-names(l.perf)
for(i in 1:length(l.perf)){
  message("Running ", unique(l.perf[[i]]$val))
  message("---> paired")
  mod<-nlme::lme(AUC ~ prof, data = l.perf[[i]], random = ~ 1 | model)
  print(car::Anova(mod))
  print(anova(mod))
  print(summary(mod))
  em<-emmeans::emmeans(object = mod, pairwise ~ prof, adjust = "fdr")
  print(em)
  l.emm[[i]]<-as.data.frame(em$contrasts)
}

df.emm<-do.call(rbind, l.emm)
df.emm$Validation.type<-c(rep("CSV", nrow(df.emm)/3),
				rep("LOSO", nrow(df.emm)/3), 
				rep("within-study CV", nrow(df.emm)/3))
write.table(df.emm, file = "/metaG/R_analyses/Functions/KO/RDS/Table.emmeans.compare.AUCs.txt",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)
```
# Prepare dataframe needed

```{r}
df.average<-ridge.all.tax.f %>%
  group_by(profile) %>%
  summarise(mean = mean(AUC))

l.average<-l.all %>%
  group_by(funct) %>%
  summarise(mean = mean(AUC))


# make df for points
df.points<-data.frame(
  study = c(ridge.all.tax.f$study, l.all$study.out),
  AUC = c(ridge.all.tax.f$AUC, l.all$AUC),
  method = c(ridge.all.tax.f$funct, l.all$funct),
  type = c(ridge.all.tax.f$type, l.all$type) %>% as.factor())
```
# Make violin plot
```{r}
# create final df
csv.all$funct<-factor(csv.all$funct, levels = c("taxonomy", "KO", "KEGGmod", "KEGGpath", "GBM", "GMM"))
df.points$method<-factor(df.points$method, levels = c("taxonomy", "KO", "KEGGmod", "KEGGpath", "GBM", "GMM"))
df.all$type<-factor(df.all$type, levels = c("within-study CV", "CSV", "LOSO"), ordered = T)

df.all<-data.frame(AUC = c(csv.all$AUC, df.points$AUC),
                   funct = c(csv.all$funct, df.points$method),
                   type = c(csv.all$type , df.points$type %>%
                              as.character()))
df.mean.std.csv <- df.all%>% 
  group_by(type, funct) %>%
  summarise(mean = mean(AUC),
            stdev = sd(AUC),
            min = min(AUC),
            max = max(AUC))
(ggplot() + 
      geom_hline(yintercept=50, linetype = "dashed", 
                color = "darkgray", size=1) +

    theme_bw() +
    # add violins
    geom_violin(data = df.all,
                mapping = aes(x = funct, 
                              y = AUC, 
                              fill = type),
                trim = T,
                size = 0.5,
                alpha = 0.2,
                position = "dodge", 
                scale = "width", show.legend = F) +
    scale_fill_manual(values = c("white", "#DCC83C", "#285AA0")) +

    # add error bar with margin
    geom_errorbar(data = df.mean.std.csv,
                  mapping = aes(x = funct,
                                ymin = mean - stdev, 
                                ymax = mean + stdev,
                                group = type), 
                  width = 0,  color = "black", size = 1.5,
                  position = position_dodge(width = 0.9)) +

    geom_errorbar(data = df.mean.std.csv,
                  mapping = aes(x = funct,
                                ymin = mean - stdev, 
                                ymax = mean + stdev,
                                color = type), 
                  width = 0, size = 1.25,
                  position = position_dodge(width = 0.9), show.legend = F) +

      # add stats summaries
    new_scale_fill() +
    geom_point(data = df.mean.std.csv, 
               mapping = aes(funct, 
                           mean,
                           fill = type),
               pch = 21,
               size = 5,
               position = position_dodge2(width = 0.9)) +
    scale_fill_manual(values = c("darkgray", "#FFED00", "#0072B2")) +
    scale_color_manual(values = c("darkgray", "#FFED00", "#0072B2")) +
    labs(
        x = "Profiles",
        fill = "ML approaches") +

  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        title = element_text(size = 14)) )




ggsave("/metaG/R_analyses/Functions/AA_KO/Figures/Functions_Only_Violin_merged.svg", 
       width = 8, 
       height = 5) 

Calculate overall means
```{r}
s16<-readRDS("/16S/R_analyses/RDS/df.comb.cv.scv.rds")
ls16<-readRDS("/16S/R_analyses/RDS/ls.out.cv.scv.rds")
s16<-subset(s16, ML == "ridge")

df.tmp<-data.frame(model =  c(s16$training.data, ls16$study.out),
                   AUC = c(s16$AUC, ls16$AUC),
                   val = c(s16$method, ls16$method),
                   prof =  rep("16S", nrow(s16) + nrow(ls16)))
df.tmp[df.tmp$val == "CV",]$val <- "within-study CV"

df.all.test.16<-rbind.data.frame(df.all.test, df.tmp)

df.all.test.16 %>%
  group_by(val, prof) %>%
  summarise(mean = mean(AUC),
            stdev = sd(AUC),
            N = n())

df.all.test.16 %>%
  group_by(val) %>%
  summarise(mean = mean(AUC),
            stdev = sd(AUC))
```
